(()=>{
const API='https://bible.helloao.org/api',params=new URLSearchParams(location.search),lang=params.get('lang')==='hi'?'hi':'en',root=document.querySelector('#bible-reader'),cache=new Map();let translations=[],books=[],translation=null,activeBook=null,activeChapter=1,requestNumber=0;
const hi=lang==='hi';
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeHttpsUrl(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:'https://bible.helloao.org/docs/'}catch{return 'https://bible.helloao.org/docs/'}}
function defaultTranslation(list){const language=hi?'hin':'eng',available=list.filter(t=>t.language===language&&t.availableFormats?.includes('json')&&t.numberOfBooks>=66).sort((a,b)=>(a.shortName||'').localeCompare(b.shortName||'')),preferred=hi?/HINOVBSI/i:/\bESV\b|ENGLISH STANDARD VERSION/i;return available.find(t=>preferred.test(`${t.id} ${t.shortName} ${t.name} ${t.englishName}`))||available.find(t=>/berean standard bible/i.test(t.englishName||''))||available[0]}
async function getJSON(path){const response=await fetch(`${API}/${path}`);if(!response.ok)throw Error(hi?'बाइबल डेटा लोड नहीं हो सका। इंटरनेट कनेक्शन जाँचें और फिर कोशिश करें।':'Bible data could not be loaded. Check your internet connection and try again.');return response.json()}
function renderShell(){document.title=`${hi?'पूरी बाइबल पढ़ें':'Read the Bible'} — ${hi?'जीवन की ज्योति':'Light of Life'}`;root.classList.toggle('hindi',hi);root.innerHTML=`<div class="bible-reader-heading"><span class="eyebrow ${hi?'hindi':''}">${hi?'पवित्रशास्त्र':'Scripture'}</span><h1>${hi?'पूरी बाइबल पढ़ें':'Read the whole Bible'}</h1></div><section class="bible-reader-controls" aria-label="${hi?'बाइबल पाठ चयन':'Bible reader controls'}"><label>${hi?'अनुवाद':'Translation'}<select id="bible-translation"></select></label><label>${hi?'पुस्तक':'Book'}<select id="bible-book"></select></label><label>${hi?'अध्याय':'Chapter'}<select id="bible-chapter"></select></label></section><div class="bible-reader-status" id="bible-reader-status" role="status" aria-live="polite"></div><article class="bible-chapter-card"><h2 id="bible-chapter-title"></h2><div id="bible-chapter-content" class="bible-chapter-content"></div><div class="bible-reader-pager"><button type="button" class="outline-btn" id="bible-previous">${hi?'← पिछला अध्याय':'← Previous chapter'}</button><button type="button" class="outline-btn" id="bible-next">${hi?'अगला अध्याय →':'Next chapter →'}</button></div><small id="bible-attribution" class="bible-attribution"></small></article>`}
function savePosition(){try{localStorage.setItem(`bible-reader-position-${lang}`,JSON.stringify({book:activeBook?.id,chapter:activeChapter}))}catch{}}
function loadTranslationOptions(){const select=root.querySelector('#bible-translation'),options=translations.filter(t=>t.language===(hi?'hin':'eng')&&t.availableFormats?.includes('json')&&t.numberOfBooks>=66).sort((a,b)=>(a.englishName||a.name).localeCompare(b.englishName||b.name));let saved='';try{saved=localStorage.getItem(`scripture-translation-${lang}`)||''}catch{}const chosen=options.find(x=>x.id===saved)||defaultTranslation(options);if(!chosen)throw Error(hi?'HelloAO में पूरी हिंदी बाइबल उपलब्ध नहीं है।':'HelloAO does not have a complete English Bible translation available.');select.innerHTML=options.map(t=>`<option value="${escapeHtml(t.id)}">${escapeHtml(t.englishName||t.name)}${t.shortName?` (${escapeHtml(t.shortName)})`:''}</option>`).join('');select.value=chosen.id;select.onchange=()=>{translation=options.find(t=>t.id===select.value);try{localStorage.setItem(`scripture-translation-${lang}`,translation.id)}catch{};loadBooks()};translation=chosen}
async function loadBooks(){const request=++requestNumber,status=root.querySelector('#bible-reader-status');status.textContent=hi?'पुस्तकें लोड हो रही हैं…':'Loading books…';root.querySelector('#bible-chapter-content').replaceChildren();try{const result=await getJSON(`${encodeURIComponent(translation.id)}/books.json`);if(request!==requestNumber)return;books=(result.books||[]).filter(book=>!book.isApocryphal);if(!books.length)throw Error(hi?'इस अनुवाद में कोई पुस्तक नहीं मिली।':'No books were found for this translation.');let saved={};try{saved=JSON.parse(localStorage.getItem(`bible-reader-position-${lang}`)||'{}')}catch{}const wanted=new URLSearchParams(location.search),bookId=wanted.get('book')||saved.book,chapterFromUrl=Number(wanted.get('chapter'))||Number(saved.chapter)||1;activeBook=books.find(book=>book.id===bookId)||books[0];activeChapter=Math.min(Math.max(1,chapterFromUrl),activeBook.numberOfChapters);const bookSelect=root.querySelector('#bible-book');bookSelect.innerHTML=books.map(book=>`<option value="${escapeHtml(book.id)}">${escapeHtml(book.commonName||book.name)}</option>`).join('');bookSelect.value=activeBook.id;bookSelect.onchange=()=>{activeBook=books.find(book=>book.id===bookSelect.value);activeChapter=1;fillChapterSelect();showChapter()};fillChapterSelect();await showChapter()}catch(error){if(request===requestNumber)status.textContent=error.message}}
function fillChapterSelect(){const select=root.querySelector('#bible-chapter');select.innerHTML=Array.from({length:activeBook.numberOfChapters},(_,i)=>`<option value="${i+1}">${hi?'अध्याय':'Chapter'} ${i+1}</option>`).join('');select.value=String(activeChapter);select.onchange=()=>{activeChapter=Number(select.value);showChapter()}}
async function showChapter(){const request=++requestNumber,status=root.querySelector('#bible-reader-status'),content=root.querySelector('#bible-chapter-content'),title=root.querySelector('#bible-chapter-title'),attrib=root.querySelector('#bible-attribution');root.querySelector('#bible-chapter').value=String(activeChapter);title.textContent=`${activeBook.commonName||activeBook.name} ${hi?'अध्याय':'Chapter'} ${activeChapter}`;content.innerHTML=`<p class="bible-loading">${hi?'अध्याय लोड हो रहा है…':'Loading chapter…'}</p>`;status.textContent='';try{const key=`${translation.id}/${activeBook.id}/${activeChapter}`,chapter=cache.get(key)||await getJSON(`${encodeURIComponent(translation.id)}/${encodeURIComponent(activeBook.id)}/${activeChapter}.simple.json`);cache.set(key,chapter);if(request!==requestNumber)return;const elements=chapter.chapter?.content||[];content.innerHTML=elements.map(item=>item.type==='verse'?`<p class="bible-reader-verse"><sup>${item.number}</sup>${escapeHtml(item.text).replace(/\n/g,'<br>')}</p>`:item.type==='heading'?`<h3 class="bible-reader-subheading">${escapeHtml(item.text)}</h3>`:item.type==='line_break'?'<div class="bible-reader-line-break" aria-hidden="true"></div>':'').join('');const license=safeHttpsUrl(translation.licenseUrl||translation.website);attrib.innerHTML=`${escapeHtml(translation.englishName||translation.name)} · ${hi?'अनुवाद का लाइसेंस:':'Translation license:'} <a href="${escapeHtml(license)}" target="_blank" rel="noopener">${hi?'विवरण देखें':'View terms'}</a> · <a href="https://bible.helloao.org/docs/?ref=faith.tools" target="_blank" rel="noopener">HelloAO API</a>`;savePosition();const index=books.findIndex(book=>book.id===activeBook.id);root.querySelector('#bible-previous').disabled=index===0&&activeChapter===1;root.querySelector('#bible-next').disabled=index===books.length-1&&activeChapter===activeBook.numberOfChapters}catch(error){if(request===requestNumber)content.innerHTML=`<p class="bible-reader-status">${escapeHtml(error.message)}</p>`}}
function moveChapter(delta){const index=books.findIndex(book=>book.id===activeBook.id);let next=activeChapter+delta;if(next<1){if(index===0)return;activeBook=books[index-1];next=activeBook.numberOfChapters;root.querySelector('#bible-book').value=activeBook.id;fillChapterSelect()}else if(next>activeBook.numberOfChapters){if(index>=books.length-1)return;activeBook=books[index+1];next=1;root.querySelector('#bible-book').value=activeBook.id;fillChapterSelect()}activeChapter=next;showChapter()}
async function start(){renderShell();root.querySelector('#bible-previous').onclick=()=>moveChapter(-1);root.querySelector('#bible-next').onclick=()=>moveChapter(1);try{const data=await getJSON('available_translations.json');translations=data.translations||[];loadTranslationOptions();await loadBooks()}catch(error){root.querySelector('#bible-reader-status').textContent=error.message}}
start();
})();
