const root=document.querySelector('#language-page'),params=new URLSearchParams(location.search),lang=params.get('lang')==='hi'?'hi':'en',data=catalog[lang];
progressStore.setLanguage(lang);
const done=progressStore.getProgress();
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function href(x){return `lesson.html?lang=${lang}&id=${encodeURIComponent(x.id)}`}
document.documentElement.lang=lang==='hi'?'hi':'en';document.title=`${data.series} — Light of Life`;
const rows=data.lessons.map(x=>{const completed=!!done[`${lang}:${x.id}`];return `<a class="lesson-row ${completed?'is-done':''}" href="${href(x)}"><span class="lesson-number">${x.number==='Intro'?'✦':String(x.number).padStart(2,'0')}</span><span><h3 class="${lang==='hi'?'hindi':''}">${esc(x.title)}</h3><p>${esc([x.ref,x.duration].filter(Boolean).join(' · ')||'Discovery Bible Series')}</p></span>${completed?`<span class="lesson-completion" role="img" aria-label="${lang==='hi'?'पूरा हुआ':'Completed'}" title="${lang==='hi'?'पूरा हुआ':'Completed'}">✓</span>`:`<span class="lesson-meta" aria-hidden="true">›</span>`}</a>`}).join('');
root.innerHTML=`<div class="page-head language-heading"><div><span class="eyebrow">${esc(data.name)} · Discovery Bible Series</span><h1 class="${lang==='hi'?'hindi':''}">${esc(data.series)}</h1><a class="playlist-link ${lang==='hi'?'hindi':''}" href="https://www.youtube.com/playlist?list=PLa0LLRCNiHpw" target="_blank" rel="noopener noreferrer">${lang==='hi'?'यूट्यूब पर प्लेलिस्ट देखें':'Watch playlist on YouTube'} <span aria-hidden="true">↗</span></a></div><img class="language-logo" src="${data.logo}" alt="${esc(data.name)} logo"><span class="pill">${data.lessons.length} ${lang==='hi'?'भाग':'parts'}</span></div><div class="lesson-list">${rows}</div><button class="drawer-toggle ${lang==='hi'?'hindi':''}" id="drawer-toggle" aria-expanded="false" aria-controls="lesson-drawer">☷ <span>${lang==='hi'?'पाठ':'Lessons'}</span></button><aside class="lesson-drawer" id="lesson-drawer" aria-label="${lang==='hi'?'पाठ चयन':'Lesson selection'}"><div class="drawer-head"><strong class="${lang==='hi'?'hindi':''}">${esc(data.series)}</strong><button id="drawer-close" aria-label="${lang==='hi'?'पाठ सूची बंद करें':'Close lesson list'}">×</button></div><nav>${data.lessons.map(x=>`<a href="${href(x)}" class="${done[`${lang}:${x.id}`]?'is-done':''}"><span>${x.number==='Intro'?'✦':String(x.number).padStart(2,'0')}</span><span class="${lang==='hi'?'hindi':''}">${esc(x.title)}</span></a>`).join('')}</nav></aside><div class="drawer-scrim" id="drawer-scrim"></div>`;
const toggle=document.querySelector('#drawer-toggle'),drawer=document.querySelector('#lesson-drawer'),scrim=document.querySelector('#drawer-scrim');function openDrawer(v){drawer.classList.toggle('open',v);scrim.classList.toggle('visible',v);toggle.setAttribute('aria-expanded',String(v))}toggle.onclick=()=>openDrawer(!drawer.classList.contains('open'));document.querySelector('#drawer-close').onclick=()=>openDrawer(false);scrim.onclick=()=>openDrawer(false);
