const CACHE='light-of-life-v63';
const LESSONS=[...Array.from({length:20},(_,i)=>`./lessons/en/lesson-${i+16}.json`),'./lessons/en/lesson-20-part-2.json','./lessons/en/lesson-23-part-2.json','./lessons/en/lesson-27-part-2.json','./lessons/en/what-next.json','./lessons/en/church-essentials.json','./lessons/en/co-workers-study.json','./lessons/en/four-fields-plan.json',...Array.from({length:20},(_,i)=>`./lessons/hi/lesson-${i+16}.json`),'./lessons/hi/lesson-20-part-2.json','./lessons/hi/lesson-23-part-2.json','./lessons/hi/lesson-27-part-2.json','./lessons/hi/what-next.json','./lessons/hi/co-workers-study.json','./lessons/hi/four-fields-plan.json','./lessons/hi/church-essentials.json'];
const MEDIA=['./assets/lesson-images/english-healthy-church-tracking.png','./assets/lesson-images/healthy-church-generations.png','./assets/lesson-images/hindi-healthy-church-tracking.png','./assets/lesson-images/healthy-church-maps.png','./assets/lesson-images/hand-numbered.png','./assets/lesson-images/lesson-16.png','./assets/lesson-images/lesson-17.png','./assets/lesson-images/lesson-18.png','./assets/lesson-images/lesson-19.png','./assets/lesson-images/lesson-20.png','./assets/lesson-images/lesson-21.png','./assets/lesson-images/lesson-22.png','./assets/lesson-images/lesson-23.png','./assets/lesson-images/lesson-24.png','./assets/lesson-images/lesson-25.png','./assets/lesson-images/lesson-26.png','./assets/lesson-images/lesson-27.png','./assets/lesson-images/lesson-28.png','./assets/lesson-images/lesson-29.png','./assets/lesson-images/lesson-30.png','./assets/lesson-images/lesson-31.png','./assets/lesson-images/lesson-32.png','./assets/lesson-images/lesson-33.png','./assets/lesson-images/lesson-34.png','./assets/lesson-images/lesson-35.png','./assets/lesson-images/english-lesson-23-part-2-testimony-question.png','./assets/lesson-images/english-lesson-what-next-groups.png','./assets/lesson-images/english-lesson-what-next-sword-questions.png','./assets/lesson-images/hindi-lesson-what-next-sword-questions.png','./assets/lesson-images/hindi-four-fields-plan.png','./assets/lesson-images/english-four-fields-plan.png','./assets/lesson-images/hindi-church-essentials-page-1.png','./assets/lesson-images/hindi-church-essentials-page-2.png','./assets/lesson-images/hindi-church-essentials-page-3.png','./assets/lesson-images/hindi-church-essentials-page-4.png','./assets/lesson-images/english-church-essentials-page-1.png','./assets/lesson-images/english-church-essentials-page-2.png','./assets/lesson-images/english-church-essentials-page-3.png','./assets/lesson-images/english-church-essentials-page-4.png'];
const SHELL=[...LESSONS,...MEDIA,'./','./index.html','./home.html','./language.html','./lesson.html','./bible.html','./styles.css','./app.js','./home-page.js','./language-page.js','./lesson-page.js','./bible-reader.js','./scripture-popups.js','./progress-store.js','./install.js','./catalog.js','./brand-language.js','./share-page.js','./header-nav.js','./text-size.js','./manifest.webmanifest','./manifest-en.webmanifest','./manifest-hi.webmanifest','./assets/english-logo.png','./assets/hindi-logo.png','./assets/group-button.png','./assets/hand-gospel/hand-01.png', './assets/hand-gospel/hand-02.png', './assets/hand-gospel/hand-03.png', './assets/hand-gospel/hand-04.png', './assets/hand-gospel/hand-05.png', './assets/hand-gospel/hand-06.png', './assets/hand-gospel/hand-07.png', './assets/hand-gospel/hand-08.png', './assets/hand-gospel/hand-09.png', './assets/hand-gospel/hand-10.png','./assets/lightoflife812-qr.png'];
// Activate new builds as soon as their app shell is cached. Existing pages are
// left running; the next page navigation loads the updated app without interrupting media.
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(event.request,{ignoreSearch:true})||caches.match('./index.html'))))});
